version: '3.0'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /febs/prometheus/:/etc/prometheus/
    ports:
      - "8403:9090"
    restart: on-failure
  node_exporter:
    image: prom/node-exporter
    ports:
      - "8405:9100"
  redis_exporter:
    image: oliver006/redis_exporter
    command:
      - '--redis.addr=redis://ip:port'
      - '--redis.password=password'
    ports:
      - "8408:9121"
    restart: on-failure
  mysql_exporter:
    image: prom/mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=username:password@(ip:port)/
    ports:
      - "8409:9104"
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8407:8080"
  alertmanager:
    image: prom/alertmanager
    volumes:
      - /febs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "8406:9093"
  grafana:
    image: grafana/grafana
    ports:
      - "8404:3000"
