global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'spring-boot-3-monolith'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-boot-3-monolith:8080']
        labels:
          application: 'spring-boot-3-monolith'
