version: '3.0'

services:
  mysql:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=chensoul
      - MYSQL_USER=chensoul
      - MYSQL_PASSWORD=chensoul
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} -e 'SHOW DATABASES;'"
      interval: 2s
      retries: 30

volumes:
  mysql-data:
