version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 123456
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    volumes:
      - ./conf/my.cnf:/etc/my.cnf
    restart: always
    ports:
      - "3306:3306"
