services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=chensoul
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd -e 'SHOW DATABASES;'"
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
