version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    restart: unless-stopped
    volumes:
      - ./nacos/logs:/home/nacos/logs
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MODE: standalone
    ports:
      - "8848:8848"
