version: '3.7'
services:
  gitlab:
    image: 'twang2218/gitlab-ce-zh:11.1.4'
    restart: always
    hostname: 'gitlab.cocktail.com'
    container_name: 'gitlab'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.cocktail.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        unicorn['port'] = 8888
        nginx['listen_port'] = 80
    ports:
      - "80:80"
      - "443:443"
      - "2222:2222"
    volumes:
      - ./config:/etc/gitlab
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
