services:
    postgres:
        image: postgres:16-alpine
        container_name: postgresql
        environment:
            - POSTGRES_DB=artifactory
            - POSTGRES_USER=artifactory
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - /etc/localtime:/etc/localtime:ro

    sonarqube:
        image: sonarqube:10.6-community
        ports:
            - "9000:9000"
        environment:
            # CREATE USER sonar WITH PASSWORD 'sonar';
            # CREATE DATABASE sonar owner sonar;
            # GRANT ALL ON SCHEMA public TO sonar;
            - SONAR_JDBC_URL=jdbc:postgresql://postgresql:5432/sonar
            - SONAR_JDBC_USERNAME=sonar
            - SONAR_JDBC_PASSWORD=sonar
        volumes:
            - sonar_data:/opt/sonarqube

volumes:
    postgres_data:
    sonar_data: