version: '3.7'
services:
  activemq:
    image: rmohr/activemq
    container_name: activemq
    restart: always
    ports:
      - "61613:61613"
      - "61616:61616"
      - "8161:8161"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_CONFIG_MINMEMORY: 512
      ACTIVEMQ_CONFIG_MAXMEMORY: 2048
