version: '3.0'
services:
  # rocketmq代理发现注册服务
  rmqnamesrv:
    image: foxiswho/rocketmq:server
    restart: always
    ports:
      - "9876:9876"
    volumes:
      - /data/rocketmq/namesrv/logs:/opt/logs
      - /data/rocketmq/namesrv/store:/opt/store

  # rocketmq核心消息发送存储代理
  rmqbroker:
    image: foxiswho/rocketmq:broker
    restart: always
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - /data/rocketmq/namesrv/logs:/opt/logs
      - /data/rocketmq/namesrv/store:/opt/store
      - /data/rocketmq/broker/brokerconf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPTS: "-Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rmqnamesrv

