version: '3.0'

services:
  # Redis cluster
  redis-node-1:
    image: bitnami/redis-cluster:7.2
    volumes:
      - redis_cluster_1_data:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=redis
      - REDISCLI_AUTH=redis
      - REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6

  redis-node-2:
    image: bitnami/redis-cluster:7.2
    volumes:
      - redis_cluster_2_data:/bitnami/redis/data
    depends_on:
      - redis-node-1
    environment:
      - REDIS_PASSWORD=redis
      - REDISCLI_AUTH=redis
      - REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6

  redis-node-3:
    image: bitnami/redis-cluster:7.2
    volumes:
      - redis_cluster_3_data:/bitnami/redis/data
    depends_on:
      - redis-node-2
    environment:
      - REDIS_PASSWORD=redis
      - REDISCLI_AUTH=redis
      - REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6

  redis-node-4:
    image: bitnami/redis-cluster:7.2
    volumes:
      - redis_cluster_4_data:/bitnami/redis/data
    depends_on:
      - redis-node-3
    environment:
      - REDIS_PASSWORD=redis
      - REDISCLI_AUTH=redis
      - REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6

  redis-node-5:
    image: bitnami/redis-cluster:7.2
    volumes:
      - redis_cluster_5_data:/bitnami/redis/data
    depends_on:
      - redis-node-4
    environment:
      - REDIS_PASSWORD=redis
      - REDISCLI_AUTH=redis
      - REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6

  redis-node-6:
    image: bitnami/redis-cluster:7.2
    volumes:
      - redis_cluster_6_data:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - REDIS_PASSWORD=redis
      - REDISCLI_AUTH=redis
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_CREATOR=yes


volumes:
  redis_cluster_1_data: 
  redis_cluster_2_data: 
  redis_cluster_3_data: 
  redis_cluster_4_data: 
  redis_cluster_5_data: 
  redis_cluster_6_data: 
