version: '3'
services:
  redis:
    image: redis:6.2.6
    container_name: redis
    hostname: redis
    restart: always
    command: redis-server /etc/redis/redis.conf --requirepass 123456 --appendonly yes
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - "./redis/config/redis.conf:/etc/redis/redis.conf"  # http://download.redis.io/redis-stable/redis.conf
    ports:
      - "6379:6379"
