version: '3.0'

services:
  # Redis sentinel
  redis-master:
    image: bitnami/redis:7.2
    volumes:
      - redis-sentinel-data-master:/bitnami/redis/data
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=123456

  redis-slave:
    image: bitnami/redis:7.2
    volumes:
      - redis-sentinel-data-slave:/bitnami/redis/data
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=123456
      - REDIS_PASSWORD=123456
    depends_on:
      - redis-master

  redis-sentinel:
    image: bitnami/redis:7.2
    volumes:
      - redis-sentinel-data-sentinel:/bitnami/redis/data
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_PASSWORD=123456
      - REDIS_MASTER_PASSWORD=123456
    depends_on:
      - redis-master
      - redis-slave

volumes:
  redis-sentinel-data-master: 
  redis-sentinel-data-slave: 
  redis-sentinel-data-sentinel: 
