version: '3.0'

services:
  # Redis standalone
  redis:
    restart: always
    image: bitnami/redis:7.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/bitnami/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli","--raw", "incr","ping" ]
      interval: 5s
      timeout: 2s
      retries: 10

volumes:
  redis-data:
